FROM node:12.18.3-slim AS init

RUN npm install -g pm2 -g

WORKDIR /var/www

##################################################################
# BUILD
##################################################################
FROM node:12.18.3-slim AS build
COPY . /var/www/.
WORKDIR /var/www

RUN yarn install && \
    npm run prebuild && \
    npm run build && \
    mkdir -p /opt/prebuild && \
    mv /var/www/* /opt/prebuild/. && \
    mv /opt/prebuild/dist /var/www/. && \
    mv /opt/prebuild/node_modules /var/www/. && \
    mv /opt/prebuild/views /var/www/. && \
    mkdir -p /var/www/var/logs && \
    rm -Rf /opt/prebuild

##################################################################
# RUN
##################################################################
FROM node:12.18.3-slim AS run
RUN  apt-get update \
     && apt-get install -y wget gnupg ca-certificates \
     && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
     && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
     && apt-get update \
     # We install Chrome to get all the OS level dependencies, but Chrome itself
     # is not actually used as it's packaged in the node puppeteer library.
     # Alternatively, we could could include the entire dep list ourselves
     # (https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix)
     # but that seems too easy to get out of date.
     && apt-get install -y google-chrome-stable \
     && rm -rf /var/lib/apt/lists/* \
     && wget --quiet https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -O /usr/sbin/wait-for-it.sh \
     && chmod +x /usr/sbin/wait-for-it.sh
RUN npm install -g pm2 -g
COPY --from=build /var/www /var/www
WORKDIR /var/www
EXPOSE 5000
CMD ["pm2-runtime", "dist/main.js"]